# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_sspLib')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_sspLib')
    _sspLib = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_sspLib', [dirname(__file__)])
        except ImportError:
            import _sspLib
            return _sspLib
        try:
            _mod = imp.load_module('_sspLib', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _sspLib = swig_import_helper()
    del swig_import_helper
else:
    import _sspLib
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class marmoteSet(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, marmoteSet, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, marmoteSet, name)
    __repr__ = _swig_repr
    UNION = _sspLib.marmoteSet_UNION
    PRODUCT = _sspLib.marmoteSet_PRODUCT
    SIMPLE = _sspLib.marmoteSet_SIMPLE

    def __init__(self, *args):
        this = _sspLib.new_marmoteSet(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _sspLib.delete_marmoteSet
    __del__ = lambda self: None

    def cardinal(self):
        return _sspLib.marmoteSet_cardinal(self)

    def isFinite(self):
        return _sspLib.marmoteSet_isFinite(self)

    def isSimple(self):
        return _sspLib.marmoteSet_isSimple(self)

    def isUnion(self):
        return _sspLib.marmoteSet_isUnion(self)

    def isProduct(self):
        return _sspLib.marmoteSet_isProduct(self)

    def totNbDims(self):
        return _sspLib.marmoteSet_totNbDims(self)

    def enumerate(self):
        return _sspLib.marmoteSet_enumerate(self)

    def test_index_decode(self):
        return _sspLib.marmoteSet_test_index_decode(self)

    def firstState(self, buffer):
        return _sspLib.marmoteSet_firstState(self, buffer)

    def nextState(self, buffer):
        return _sspLib.marmoteSet_nextState(self, buffer)

    def decodeState(self, index, buffer):
        return _sspLib.marmoteSet_decodeState(self, index, buffer)

    def index(self, buffer):
        return _sspLib.marmoteSet_index(self, buffer)

    def isZero(self, buffer):
        return _sspLib.marmoteSet_isZero(self, buffer)

    def printState(self, *args):
        return _sspLib.marmoteSet_printState(self, *args)
marmoteSet_swigregister = _sspLib.marmoteSet_swigregister
marmoteSet_swigregister(marmoteSet)

class marmoteInterval(marmoteSet):
    __swig_setmethods__ = {}
    for _s in [marmoteSet]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, marmoteInterval, name, value)
    __swig_getmethods__ = {}
    for _s in [marmoteSet]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, marmoteInterval, name)
    __repr__ = _swig_repr

    def __init__(self, min, max):
        this = _sspLib.new_marmoteInterval(min, max)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _sspLib.delete_marmoteInterval
    __del__ = lambda self: None

    def isFinite(self):
        return _sspLib.marmoteInterval_isFinite(self)

    def isZero(self, buffer):
        return _sspLib.marmoteInterval_isZero(self, buffer)

    def firstState(self, buffer):
        return _sspLib.marmoteInterval_firstState(self, buffer)

    def nextState(self, buffer):
        return _sspLib.marmoteInterval_nextState(self, buffer)

    def decodeState(self, index, buffer):
        return _sspLib.marmoteInterval_decodeState(self, index, buffer)

    def index(self, buffer):
        return _sspLib.marmoteInterval_index(self, buffer)

    def printState(self, out, buffer):
        return _sspLib.marmoteInterval_printState(self, out, buffer)

    def enumerate(self):
        return _sspLib.marmoteInterval_enumerate(self)
marmoteInterval_swigregister = _sspLib.marmoteInterval_swigregister
marmoteInterval_swigregister(marmoteInterval)

class transitionStructure(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, transitionStructure, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, transitionStructure, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _sspLib.delete_transitionStructure
    __del__ = lambda self: None

    def size(self):
        return _sspLib.transitionStructure_size(self)

    def origSize(self):
        return _sspLib.transitionStructure_origSize(self)

    def destSize(self):
        return _sspLib.transitionStructure_destSize(self)

    def type(self):
        return _sspLib.transitionStructure_type(self)

    def uniformizationRate(self):
        return _sspLib.transitionStructure_uniformizationRate(self)

    def setType(self, t):
        return _sspLib.transitionStructure_setType(self, t)

    def setUniformizationRate(self, rate):
        return _sspLib.transitionStructure_setUniformizationRate(self, rate)

    def setEntry(self, i, j, val):
        return _sspLib.transitionStructure_setEntry(self, i, j, val)

    def getEntry(self, i, j):
        return _sspLib.transitionStructure_getEntry(self, i, j)

    def getNbElts(self, i):
        return _sspLib.transitionStructure_getNbElts(self, i)

    def getCol(self, i, k):
        return _sspLib.transitionStructure_getCol(self, i, k)

    def getEntryByCol(self, i, k):
        return _sspLib.transitionStructure_getEntryByCol(self, i, k)

    def getTransDistrib(self, i):
        return _sspLib.transitionStructure_getTransDistrib(self, i)

    def readEntry(self, input):
        return _sspLib.transitionStructure_readEntry(self, input)

    def rowSum(self, i):
        return _sspLib.transitionStructure_rowSum(self, i)

    def copy(self):
        return _sspLib.transitionStructure_copy(self)

    def uniformize(self):
        return _sspLib.transitionStructure_uniformize(self)

    def embed(self):
        return _sspLib.transitionStructure_embed(self)

    def evaluateMeasure(self, *args):
        return _sspLib.transitionStructure_evaluateMeasure(self, *args)

    def evaluateValue(self, v, res):
        return _sspLib.transitionStructure_evaluateValue(self, v, res)

    def write(self, out, format):
        return _sspLib.transitionStructure_write(self, out, format)

    def toString(self, format):
        return _sspLib.transitionStructure_toString(self, format)
transitionStructure_swigregister = _sspLib.transitionStructure_swigregister
transitionStructure_swigregister(transitionStructure)

class SCC(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SCC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SCC, name)
    __repr__ = _swig_repr
    __swig_setmethods__["id"] = _sspLib.SCC_id_set
    __swig_getmethods__["id"] = _sspLib.SCC_id_get
    if _newclass:
        id = _swig_property(_sspLib.SCC_id_get, _sspLib.SCC_id_set)
    __swig_setmethods__["period"] = _sspLib.SCC_period_set
    __swig_getmethods__["period"] = _sspLib.SCC_period_get
    if _newclass:
        period = _swig_property(_sspLib.SCC_period_get, _sspLib.SCC_period_set)
    __swig_setmethods__["states"] = _sspLib.SCC_states_set
    __swig_getmethods__["states"] = _sspLib.SCC_states_get
    if _newclass:
        states = _swig_property(_sspLib.SCC_states_get, _sspLib.SCC_states_set)

    def __lt__(self, a):
        return _sspLib.SCC___lt__(self, a)

    def __init__(self):
        this = _sspLib.new_SCC()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _sspLib.delete_SCC
    __del__ = lambda self: None
SCC_swigregister = _sspLib.SCC_swigregister
SCC_swigregister(SCC)

class sparseMatrix(transitionStructure):
    __swig_setmethods__ = {}
    for _s in [transitionStructure]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, sparseMatrix, name, value)
    __swig_getmethods__ = {}
    for _s in [transitionStructure]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, sparseMatrix, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _sspLib.new_sparseMatrix(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _sspLib.delete_sparseMatrix
    __del__ = lambda self: None

    def setEntry(self, row, col, val):
        return _sspLib.sparseMatrix_setEntry(self, row, col, val)

    def getEntry(self, arg2, arg3):
        return _sspLib.sparseMatrix_getEntry(self, arg2, arg3)

    def getNbElts(self, row):
        return _sspLib.sparseMatrix_getNbElts(self, row)

    def getCol(self, row, numCol):
        return _sspLib.sparseMatrix_getCol(self, row, numCol)

    def getEntryByCol(self, row, numCol):
        return _sspLib.sparseMatrix_getEntryByCol(self, row, numCol)

    def getTransDistrib(self, row):
        return _sspLib.sparseMatrix_getTransDistrib(self, row)

    def rowSum(self, row):
        return _sspLib.sparseMatrix_rowSum(self, row)

    def evaluateMeasure(self, *args):
        return _sspLib.sparseMatrix_evaluateMeasure(self, *args)

    def evaluateValue(self, v, res):
        return _sspLib.sparseMatrix_evaluateValue(self, v, res)

    def evaluateValueState(self, v, stateIndex):
        return _sspLib.sparseMatrix_evaluateValueState(self, v, stateIndex)

    def copy(self):
        return _sspLib.sparseMatrix_copy(self)

    def uniformize(self):
        return _sspLib.sparseMatrix_uniformize(self)

    def embed(self):
        return _sspLib.sparseMatrix_embed(self)

    def diagnose(self, out):
        return _sspLib.sparseMatrix_diagnose(self, out)

    def write(self, out, format):
        return _sspLib.sparseMatrix_write(self, out, format)

    def addToEntry(self, row, col, val):
        return _sspLib.sparseMatrix_addToEntry(self, row, col, val)

    def normalize(self):
        return _sspLib.sparseMatrix_normalize(self)

    def getStronglyConnectedComponents(self, ignore=0.0):
        return _sspLib.sparseMatrix_getStronglyConnectedComponents(self, ignore)
sparseMatrix_swigregister = _sspLib.sparseMatrix_swigregister
sparseMatrix_swigregister(sparseMatrix)

DISCRETE = _sspLib.DISCRETE
CONTINUOUS = _sspLib.CONTINUOUS
UNKNOWN = _sspLib.UNKNOWN
INFINITE_STATE_SPACE_SIZE = _sspLib.INFINITE_STATE_SPACE_SIZE
class solutionMDP(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, solutionMDP, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, solutionMDP, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _sspLib.new_solutionMDP()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _sspLib.delete_solutionMDP
    __del__ = lambda self: None

    def writeSolution(self):
        return _sspLib.solutionMDP_writeSolution(self)

    def setSize(self, s):
        return _sspLib.solutionMDP_setSize(self, s)
solutionMDP_swigregister = _sspLib.solutionMDP_swigregister
solutionMDP_swigregister(solutionMDP)

class genericMDP(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, genericMDP, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, genericMDP, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def writeMDP(self):
        return _sspLib.genericMDP_writeMDP(self)
    __swig_destroy__ = _sspLib.delete_genericMDP
    __del__ = lambda self: None

    def cost_perStage(self, rews):
        return _sspLib.genericMDP_cost_perStage(self, rews)

    def clearRew(self):
        return _sspLib.genericMDP_clearRew(self)

    def valueIteration(self, epsilon, maxIter):
        return _sspLib.genericMDP_valueIteration(self, epsilon, maxIter)

    def valueIterationGS(self, epsilon, maxIter):
        return _sspLib.genericMDP_valueIterationGS(self, epsilon, maxIter)

    def policyIterationModified(self, epsilon, maxIter, delta, moyIter):
        return _sspLib.genericMDP_policyIterationModified(self, epsilon, maxIter, delta, moyIter)

    def policyIteration(self, maxIter):
        return _sspLib.genericMDP_policyIteration(self, maxIter)

    def policyCost(self, policy, epsilon, maxIter):
        return _sspLib.genericMDP_policyCost(self, policy, epsilon, maxIter)
genericMDP_swigregister = _sspLib.genericMDP_swigregister
genericMDP_swigregister(genericMDP)

class averageMDP(genericMDP):
    __swig_setmethods__ = {}
    for _s in [genericMDP]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, averageMDP, name, value)
    __swig_getmethods__ = {}
    for _s in [genericMDP]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, averageMDP, name)
    __repr__ = _swig_repr

    def writeMDP(self):
        return _sspLib.averageMDP_writeMDP(self)

    def __init__(self, *args):
        this = _sspLib.new_averageMDP(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _sspLib.delete_averageMDP
    __del__ = lambda self: None

    def changeIndex(self, index):
        return _sspLib.averageMDP_changeIndex(self, index)

    def valueIteration(self, epsilon, maxIter):
        return _sspLib.averageMDP_valueIteration(self, epsilon, maxIter)

    def valueIterationGS(self, epsilon, maxIter):
        return _sspLib.averageMDP_valueIterationGS(self, epsilon, maxIter)

    def relativeValueIteration(self, epsilon, maxIter):
        return _sspLib.averageMDP_relativeValueIteration(self, epsilon, maxIter)

    def policyIteration(self, maxIter):
        return _sspLib.averageMDP_policyIteration(self, maxIter)

    def policyCost(self, policy, epsilon, maxIter):
        return _sspLib.averageMDP_policyCost(self, policy, epsilon, maxIter)

    def policyIterationModified(self, epsilon, maxIter, delta, maxInIter):
        return _sspLib.averageMDP_policyIterationModified(self, epsilon, maxIter, delta, maxInIter)
averageMDP_swigregister = _sspLib.averageMDP_swigregister
averageMDP_swigregister(averageMDP)

class totalRewardMDP(genericMDP):
    __swig_setmethods__ = {}
    for _s in [genericMDP]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, totalRewardMDP, name, value)
    __swig_getmethods__ = {}
    for _s in [genericMDP]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, totalRewardMDP, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _sspLib.delete_totalRewardMDP
    __del__ = lambda self: None

    def writeMDP(self):
        return _sspLib.totalRewardMDP_writeMDP(self)

    def valueIteration(self, epsilon, maxIter):
        return _sspLib.totalRewardMDP_valueIteration(self, epsilon, maxIter)

    def valueIterationGS(self, epsilon, maxIter):
        return _sspLib.totalRewardMDP_valueIterationGS(self, epsilon, maxIter)

    def policyIteration(self, maxIter):
        return _sspLib.totalRewardMDP_policyIteration(self, maxIter)

    def policyIterationModified(self, epsilon, maxIter, delta, maxInIter):
        return _sspLib.totalRewardMDP_policyIterationModified(self, epsilon, maxIter, delta, maxInIter)
totalRewardMDP_swigregister = _sspLib.totalRewardMDP_swigregister
totalRewardMDP_swigregister(totalRewardMDP)


def verifVd(arg1, arg2):
    return _sspLib.verifVd(arg1, arg2)
verifVd = _sspLib.verifVd

def verifVi(arg1, arg2):
    return _sspLib.verifVi(arg1, arg2)
verifVi = _sspLib.verifVi

def verifMat(arg1, arg2):
    return _sspLib.verifMat(arg1, arg2)
verifMat = _sspLib.verifMat

def verifMat2D(arg1, arg2, arg3):
    return _sspLib.verifMat2D(arg1, arg2, arg3)
verifMat2D = _sspLib.verifMat2D

def verifMatP(arg1, arg2):
    return _sspLib.verifMatP(arg1, arg2)
verifMatP = _sspLib.verifMatP

def produitMatVect(arg1, arg2, arg3):
    return _sspLib.produitMatVect(arg1, arg2, arg3)
produitMatVect = _sspLib.produitMatVect

def produitMatMat(arg1, arg2, arg3):
    return _sspLib.produitMatMat(arg1, arg2, arg3)
produitMatMat = _sspLib.produitMatMat

def prodScalV(arg1, arg2):
    return _sspLib.prodScalV(arg1, arg2)
prodScalV = _sspLib.prodScalV

def Norm(arg1, arg2, arg3):
    return _sspLib.Norm(arg1, arg2, arg3)
Norm = _sspLib.Norm

def Span(arg1, arg2, arg3):
    return _sspLib.Span(arg1, arg2, arg3)
Span = _sspLib.Span

def SpanRecup(U, V, Size, max, min):
    return _sspLib.SpanRecup(U, V, Size, max, min)
SpanRecup = _sspLib.SpanRecup

def Transpose(arg1, arg2):
    return _sspLib.Transpose(arg1, arg2)
Transpose = _sspLib.Transpose

def ResolutionSysLin(arg1, arg2, arg3):
    return _sspLib.ResolutionSysLin(arg1, arg2, arg3)
ResolutionSysLin = _sspLib.ResolutionSysLin

def Inversion(arg1, arg2, arg3):
    return _sspLib.Inversion(arg1, arg2, arg3)
Inversion = _sspLib.Inversion

def CalculPI(arg1, arg2):
    return _sspLib.CalculPI(arg1, arg2)
CalculPI = _sspLib.CalculPI

def CalculPIChaine(arg1, arg2):
    return _sspLib.CalculPIChaine(arg1, arg2)
CalculPIChaine = _sspLib.CalculPIChaine
class nonStationarySolutionMDP(solutionMDP):
    __swig_setmethods__ = {}
    for _s in [solutionMDP]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, nonStationarySolutionMDP, name, value)
    __swig_getmethods__ = {}
    for _s in [solutionMDP]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, nonStationarySolutionMDP, name)
    __repr__ = _swig_repr

    def __init__(self, h):
        this = _sspLib.new_nonStationarySolutionMDP(h)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _sspLib.delete_nonStationarySolutionMDP
    __del__ = lambda self: None

    def writeSolution(self):
        return _sspLib.nonStationarySolutionMDP_writeSolution(self)

    def setAction(self, step, a):
        return _sspLib.nonStationarySolutionMDP_setAction(self, step, a)

    def setValue(self, step, t):
        return _sspLib.nonStationarySolutionMDP_setValue(self, step, t)

    def setActionIndex(self, step, indice, value):
        return _sspLib.nonStationarySolutionMDP_setActionIndex(self, step, indice, value)

    def getActionIndex(self, step, indice):
        return _sspLib.nonStationarySolutionMDP_getActionIndex(self, step, indice)
nonStationarySolutionMDP_swigregister = _sspLib.nonStationarySolutionMDP_swigregister
nonStationarySolutionMDP_swigregister(nonStationarySolutionMDP)

class feedbackSolutionMDP(solutionMDP):
    __swig_setmethods__ = {}
    for _s in [solutionMDP]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, feedbackSolutionMDP, name, value)
    __swig_getmethods__ = {}
    for _s in [solutionMDP]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, feedbackSolutionMDP, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _sspLib.new_feedbackSolutionMDP()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _sspLib.delete_feedbackSolutionMDP
    __del__ = lambda self: None

    def setAction(self, a):
        return _sspLib.feedbackSolutionMDP_setAction(self, a)

    def setValue(self, t):
        return _sspLib.feedbackSolutionMDP_setValue(self, t)

    def setActionIndex(self, indice, value):
        return _sspLib.feedbackSolutionMDP_setActionIndex(self, indice, value)

    def getActionIndex(self, indice):
        return _sspLib.feedbackSolutionMDP_getActionIndex(self, indice)

    def getValueIndex(self, indice):
        return _sspLib.feedbackSolutionMDP_getValueIndex(self, indice)

    def writeSolution(self):
        return _sspLib.feedbackSolutionMDP_writeSolution(self)
feedbackSolutionMDP_swigregister = _sspLib.feedbackSolutionMDP_swigregister
feedbackSolutionMDP_swigregister(feedbackSolutionMDP)

class discountedMDP(genericMDP):
    __swig_setmethods__ = {}
    for _s in [genericMDP]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, discountedMDP, name, value)
    __swig_getmethods__ = {}
    for _s in [genericMDP]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, discountedMDP, name)
    __repr__ = _swig_repr

    def writeMDP(self):
        return _sspLib.discountedMDP_writeMDP(self)

    def __init__(self, *args):
        this = _sspLib.new_discountedMDP(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _sspLib.delete_discountedMDP
    __del__ = lambda self: None

    def valueIteration(self, epsilon, maxIter):
        return _sspLib.discountedMDP_valueIteration(self, epsilon, maxIter)

    def valueIterationGS(self, epsilon, maxIter):
        return _sspLib.discountedMDP_valueIterationGS(self, epsilon, maxIter)

    def policyIterationModified(self, epsilon, maxIter, delta, maxInIter):
        return _sspLib.discountedMDP_policyIterationModified(self, epsilon, maxIter, delta, maxInIter)

    def policyIteration(self, maxIter):
        return _sspLib.discountedMDP_policyIteration(self, maxIter)

    def policyCost(self, policy, epsilon, maxIter):
        return _sspLib.discountedMDP_policyCost(self, policy, epsilon, maxIter)

    def policyCostbyIndex(self, policy, epsilon, maxIter):
        return _sspLib.discountedMDP_policyCostbyIndex(self, policy, epsilon, maxIter)
discountedMDP_swigregister = _sspLib.discountedMDP_swigregister
discountedMDP_swigregister(discountedMDP)

# This file is compatible with both classic and new-style classes.


